name: auto-create-pr-after-merge
description: Create PR to default branch automatically after merge a PR to a target branch
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Create or update back-merge PR
      uses: peter-evans/create-pull-request@v8
      with:
        branch: feature/sync_to_dev
        base: ${{ github.event.repository.default_branch }}
        title: "Sync ${{ env.GITHUB_REF_NAME }} into ${{ github.event.repository.default_branch }}"
        body: |
          Automated PR to sync changes from `${{ env.GITHUB_REF_NAME }}` back into `${{ github.event.repository.default_branch }}`.
        commit-message: "sync back-merge ${{ env.GITHUB_REF_NAME }} into ${{ github.event.repository.default_branch }}"
        delete-branch: true
        sign-commits: true